project:
  type: tutorial-template

repo-url: https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub

website:
  title: "Introduction to Version Control with Git and GitHub within RStudio"
  page-footer:
    border: false
    center: "© 2026 Mike Croucher and Malika Ihle. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0."
  repo-url: https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub
          - text: Report a Bug
            href: https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: docked
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorial"
        contents:
          - href: installing-software.qmd
            text: "Installing R and RStudio"
          - href: installing-git.qmd
            text: "Installing and configuring Git"
          - href: github.qmd
            text: "Getting an account on GitHub"
          - href: ssh.qmd
            text: "Securing your connection to GitHub"
          - href: rstudio-project.qmd
            text: "Creating an RStudio project"
          - href: analysis-start.qmd
            text: "Starting our analysis project"
          - href: version-control.qmd
            text: "Getting our project under version control"
          - href: making-change.qmd
            text: "Making some changes"
          - href: commit.qmd
            text: "Committing our change"
          - href: viewing-history.qmd
            text: "Viewing history"
          - href: github-sync.qmd
            text: "Connecting our local repository to GitHub"
          - href: updates.qmd
            text: "Subsequent updates"
          - href: next-steps.qmd
            text: "Things we haven’t told you"

include-in-header:
  - file: matomo-analytics.html

include-after-body:
  - file: footer/footer.html

format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css

editor: source

bibliography: references.bib
