---
title: "Things we haven't told you"
format: html
---


You've come a long way! You've installed and configured all the software you need and have learned the basics required to put your code under version control and make it openly available to the world.

As you've seen, the standard git workflow is fairly straightforward and adds very little overhead to your workflow once you're set up. 

Git and GitHub are extremely powerful systems and there is a lot more you can learn if you wish. Here are some pointers:-

* Learn command line git by following this tutorial from Software Carpentry - <a href="http://swcarpentry.github.io/git-novice/" target ="_blank">http://swcarpentry.github.io/git-novice/</a>
* Make your analysis citable and more discoverable by using Zenodo to assign it a Digital Object Identifier - <a href="https://zenodo.org/features" target ="_blank">https://zenodo.org/features</a>

**Testing and version control**

By employing testing, you can ensure that your code behaves the way you expect.

* Unit testing in R, the bare minimum - <a href="http://www.johnmyleswhite.com/notebook/2010/08/17/unit-testing-in-r-the-bare-minimum/" target ="_blank">http://www.johnmyleswhite.com/notebook/2010/08/17/unit-testing-in-r-the-bare-minimum/</a>
* Continuous Integration. Every time you push a change to GitHub, your tests are automatically run. - <a href="https://docs.travis-ci.com/user/languages/r" target ="_blank">https://docs.travis-ci.com/user/languages/r</a>

**Dealing with dependencies**

Your code works on your machine but not on someone else's because they are using a different version of R and have different versions of packages installed. How might we fix this?

* <a href="https://lmu-osc.github.io/introduction-to-renv/" target ="_blank">https://lmu-osc.github.io/introduction-to-renv/</a> - renv enhances your project directory by storing your package dependencies inside it.

***
::: {style="text-align: right"}
[Go to the second tutorial!](https://lmu-osc.github.io/Collaborative-RStudio-GitHub/){.btn .btn-success .btn role="button"}
:::



 
